import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  quickstartSidebar: [
    {
      type: 'autogenerated',
      dirName: 'quickstart',
    },
  ],
  specSidebar: [
    {
      type: 'autogenerated',
      dirName: 'spec',
    },
  ],
  handsonSidebar: [
    {
      type: 'autogenerated',
      dirName: 'handson',
    },
    {
      // Course C is Part 2 of the exercises booklet, not a page of its own.
      type: 'link',
      label: 'Course C — Your own SoS',
      href: '/docs/handson/exercises/#course-c',
    },
  ],
};

export default sidebars;
