import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  quickstartSidebar: [
    {
      type: 'autogenerated',
      dirName: 'quickstart',
    },
  ],
  specSidebar: [
    {
      type: 'autogenerated',
      dirName: 'spec',
    },
  ],
  handsonSidebar: [
    {
      type: 'autogenerated',
      dirName: 'handson',
    },
  ],
};

export default sidebars;
