import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  specSidebar: [
    {
      type: 'autogenerated',
      dirName: 'spec',
    },
  ],
};

export default sidebars;
